Repository OriOri-CCP7/oriori, pull requests merged in 2023-06, with the labels that each got.

#12 5 write endpoints
  api/urls.py
  api/views.py
  base/migrations/0002_rename_product_id_favorite_product_and_more.py
  base/models.py
  base/serializers.py
  config/urls.py
Labels: enhancement

#25 16 setup django to display react client on site access
  .gitignore
  Dockerfile
  api/urls.py
  client/package-lock.json
  client/package.json
  client/postbuild.sh
  client/src/App.tsx
  config/settings.py
  config/urls.py
  config/views.py
  docker-compose.yml
  fly.toml
  requirements.txt
Labels: enhancement

#32 31 build client deploy
  .github/workflows/fly.yml
Labels: bug, workspace

#33 ci: add npm cache dependency path
  .github/workflows/fly.yml
Labels: bug, workspace

#35 31 build client deploy
  Dockerfile
Labels: bug, workspace

#36 build: move migrate and collectstatic to fly.sh shell script
  Dockerfile
  fly.sh
  fly.toml
Labels: bug, workspace

#37 17 seedfile init
  base/fixtures/001_Locations.json
  base/fixtures/002_Users.json
  base/fixtures/003_Stores.json
  base/fixtures/004_Products.json
  base/fixtures/005_Favorites.json
Labels: workspace

#30 15 create card component
  client/src/App.tsx
  client/src/components/Card.css
  client/src/components/Card.tsx
  client/src/pages/TestsPage.tsx
Labels: enhancement

#42 ci: temporarily allow unused-vars and exhaustive-deps
  client/package.json
Labels: bug, workspace

#43 feat: change card bg color according to distribution period
  client/src/components/Card.css
  client/src/components/Card.tsx
  client/src/components/FavButton.css
  client/src/components/FavButton.tsx
  rundev.sh
Labels: enhancement

#44 39 create prefecture picker component
  client/src/components/DropdownMenu.css
  client/src/components/DropdownMenu.tsx
  client/src/data/prefectures.json
  client/src/pages/TestsPage.tsx
Labels: enhancement, high priority

#46 Resolves #18, 19 create signup & login pages
  api/views.py
  client/.env.sample
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/components/Button.css
  client/src/components/Button.tsx
  client/src/components/Input.css
  client/src/components/Input.tsx
  client/src/context/AuthContext.tsx
  client/src/firebase.config.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.css
  client/src/pages/Login.tsx
  client/src/pages/PasswordReset.jsx
  client/src/pages/Signup.css
  client/src/pages/Signup.tsx
  client/tsconfig.json
Labels: enhancement, high priority

#56 46 Rewrite endpoints to be RESTful
  api/urls.py
  api/views.py
  client/src/context/AuthContext.tsx
  client/src/pages/Favorites.tsx
  client/src/pages/Popular.tsx
Labels: enhancement

#67 Revert ci changes
  .github/workflows/fly.yml
Labels: workspace

#57 24 create settings page
  .gitignore
  api/views.py
  client/src/App.tsx
  client/src/components/DropdownMenu.tsx
  client/src/context/AuthContext.tsx
  client/src/pages/Search.tsx
  client/src/pages/Settings.css
  client/src/pages/Settings.tsx
  client/src/pages/TestsPage.tsx
Labels: enhancement, high priority

#69 Remove Navbar from util pages & always highlight current page icon
  client/src/App.tsx
  client/src/components/Navbar.tsx
  client/src/pages/Favorites.tsx
  client/src/pages/Home.tsx
  client/src/pages/Popular.tsx
  client/src/pages/Search.tsx
Labels: bug

#79 Create onboarding page; use AuthContext to manage state of User info
  base/migrations/0003_load_prefectures.py
  client/src/App.css
  client/src/App.tsx
  client/src/components/DropdownMenu.tsx
  client/src/context/AuthContext.tsx
  client/src/firebase.config.tsx
  client/src/pages/Favorites.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.tsx
  client/src/pages/Onboarding.css
  client/src/pages/Onboarding.tsx
  client/src/pages/Popular.tsx
  client/src/pages/Search.tsx
  client/src/pages/Settings.tsx
Labels: bug, enhancement, high priority

#87 Persist user auth on refresh/navigate
  client/src/components/Grid.tsx
  client/src/context/AuthContext.tsx
  client/src/context/FavContext.tsx
  client/src/context/ProtectedRoute.tsx
  client/src/pages/Popular.tsx
Labels: enhancement

#88 86 unique favorites
  base/migrations/0004_favorite_unique_favorite.py
  base/models.py
Labels: bug, high priority

#95 68 revert ci
  .github/workflows/fly.yml
  Dockerfile
  runserver.sh
Labels: bug, workspace, high priority

#97 96 Allow empty option for DropdownMenu; Migrate Product table to reference Location directly, allow null dates
  api/views.py
  base/fixtures/004_Products.json
  base/migrations/0007_alter_product_store_alter_store_location_and_more.py
  base/migrations/0008_remove_product_store_product_location_and_more.py
  base/models.py
  client/src/@types/common.d.ts
  client/src/components/Button.tsx
  client/src/components/DropdownMenu.tsx
  client/src/components/FavButton.css
  client/src/components/FavButton.tsx
  client/src/components/ProductCard.css
  client/src/components/ProductCard.tsx
  client/src/components/ProductGrid.tsx
  client/src/pages/EditReview.tsx
  client/src/pages/Onboarding.tsx
  client/src/pages/Search.tsx
  client/src/pages/Settings.tsx
Labels: bug

#106 99 Change Favorites to Bookmarks
  api/urls.py
  api/views.py
  base/admin.py
  base/fixtures/005_Bookmarks.json
  base/migrations/0009_rename_favorite_bookmark_and_more.py
  base/models.py
  base/serializers.py
  client/src/@types/common.d.ts
  client/src/App.tsx
  client/src/components/BkmarkButton.css
  client/src/components/BkmarkButton.tsx
  client/src/components/FavButton.css
  client/src/components/FavButton.tsx
  client/src/components/Navbar.css
  client/src/components/Navbar.tsx
  client/src/components/ProductCard.tsx
  client/src/components/ProductGrid.tsx
  client/src/context/BkmarkContext.tsx
  client/src/context/FavContext.tsx
  client/src/pages/Bookmarks.css
  client/src/pages/Bookmarks.tsx
Labels: enhancement, high priority

#108 101 Add Like button
  api/urls.py
  api/views.py
  base/admin.py
  base/fixtures/006_Logs.json
  base/migrations/0011_log_liked_it_delete_review.py
  base/models.py
  base/serializers.py
  client/src/@types/common.d.ts
  client/src/components/LikeButton.css
  client/src/components/LikeButton.tsx
  client/src/components/ProductCard.tsx
  client/src/context/LogContext.tsx
Labels: enhancement, high priority

#114 110 Redesign ProductCard
  client/public/index.html
  client/public/manifest.json
  client/src/components/BkmarkButton.css
  client/src/components/BkmarkButton.tsx
  client/src/components/LikeButton.css
  client/src/components/LikeButton.tsx
  client/src/components/LogButton.css
  client/src/components/LogButton.tsx
  client/src/components/ProductCard.css
  client/src/components/ProductCard.tsx
  client/src/index.css
Labels: enhancement, high priority

#115 103 update layout of home header
  client/src/components/HomePageHeader.css
  client/src/components/HomePageHeader.tsx
  client/src/pages/Home.css
  client/src/pages/Home.tsx
Labels: enhancement

#121 feat: update base/fixtures/004_Products.json
  base/fixtures/004_Products.json
Labels: enhancement

#128 fix: update cloudinary urls in fixture 004_Products.json
  base/fixtures/004_Products.json
Labels: bug, high priority

#133 111 add logo
  client/public/oriori-logo.svg
  client/src/components/Header.tsx
  client/src/components/HomePageHeader.tsx
  client/src/pages/Login.tsx
  client/src/pages/Signup.tsx
  client/src/styles/Header.css
  client/src/styles/HomePageHeader.css
Labels: enhancement, high priority

#140 Internal Add Product flow
  client/public/index.html
  client/public/oriori-logo.svg
  client/src/@types/common.d.ts
  client/src/App.tsx
  client/src/components/Input.tsx
  client/src/components/MUITransferList.tsx
  client/src/components/ProductGrid.tsx
  client/src/constants/roles.ts
  client/src/context/AdminRoute.tsx
  client/src/context/AuthContext.tsx
  client/src/pages/AdminAddProduct.tsx
  client/src/pages/Login.tsx
  client/src/pages/Signup.tsx
  client/src/styles/AdminAddProduct.css
  client/src/styles/Button.css
  client/src/styles/DropdownMenu.css
  client/src/styles/Footer.css
  client/src/styles/Header.css
  client/src/styles/HomePageHeader.css
  client/src/styles/Input.css
Labels: enhancement, high priority

#141 134 signup flow
  client/src/components/Input.tsx
  client/src/components/ProductGrid.tsx
  client/src/context/AdminRoute.tsx
  client/src/context/AuthContext.tsx
  client/src/context/BkmarkContext.tsx
  client/src/context/LogContext.tsx
  client/src/context/ProtectedRoute.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.tsx
  client/src/pages/Onboarding.tsx
  client/src/pages/PasswordReset.tsx
  client/src/pages/Signup.tsx
  rundev.sh
Labels: bug, high priority

#151 Adjust product availability indicator colors
  client/src/components/ProductCard.tsx
  client/src/styles/ProductCard.css
Labels: enhancement, high priority

#146 145 improve onboarding page
  client/src/components/DropdownMenu.tsx
  client/src/pages/Onboarding.tsx
  client/src/styles/Onboarding.css
Labels: enhancement, high priority

#147 135 move logout button to settings page
  client/src/components/Header.tsx
  client/src/components/HomePageHeader.tsx
  client/src/pages/Settings.tsx
  client/src/styles/Button.css
  client/src/styles/DropdownMenu.css
  client/src/styles/Header.css
  client/src/styles/HomePageHeader.css
  client/src/styles/Input.css
Labels: enhancement, high priority

#159 148 additional styling
  README.md
  client/public/icon1024.jpg
  client/public/index.html
  client/public/manifest.json
  client/public/oriori-logo.svg
  client/src/App.css
  client/src/components/DropdownMenu.tsx
  client/src/components/Header.tsx
  client/src/components/HomePageHeader.tsx
  client/src/components/Input.tsx
  client/src/components/MUITransferList.tsx
  client/src/components/Navbar.tsx
  client/src/components/ProductCard.tsx
  client/src/components/ProductGrid.tsx
  client/src/components/SettingsButton.tsx
  client/src/index.css
  client/src/pages/AdminAddProduct.tsx
  client/src/pages/Bookmarks.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.tsx
  client/src/pages/Logs.tsx
  client/src/pages/Onboarding.tsx
  client/src/pages/PasswordReset.tsx
  client/src/pages/Popular.tsx
  client/src/pages/Search.tsx
  client/src/pages/Settings.tsx
  client/src/pages/Signup.tsx
  client/src/styles/AdminAddProduct.css
  client/src/styles/BkmarkButton.css
  client/src/styles/Button.css
  client/src/styles/Card.css
  client/src/styles/DropdownMenu.css
  client/src/styles/Footer.css
  client/src/styles/Header.css
  client/src/styles/HomePageHeader.css
  client/src/styles/Input.css
  client/src/styles/LikeButton.css
  client/src/styles/LogButton.css
  client/src/styles/Login.css
  client/src/styles/Navbar.css
  client/src/styles/Onboarding.css
  client/src/styles/ProductCard.css
  client/src/styles/Search.css
  client/src/styles/Settings.css
  client/src/styles/SettingsButton.css
  client/src/styles/ShareButton.css
  client/src/styles/Signup.css
  oriori-logo.png
Labels: enhancement, high priority

#166 fix: use singular 'day' when one day remains for product availability
  client/src/components/ProductCard.tsx
Labels: bug, high priority

#167 Readme edits
  README.md
  client/.env.example
  oriori-logo.png
Labels: documentation
